test: add integration tests
aws-deadline/deadline-cloud-for-blender pull request #161
Opened 2024-12-20 17:13 UTC by edwards-aws

### What was the problem/requirement? (What/Why)
We need integration tests that test how our submitter and adaptor interact with Blender

### What was the solution? (How)
Add tests 😄.

This is a first stab at adding integration tests to Blender. You can run all of the tests with `hatch run integ:test`, submitter tests only with `hatch run integ:test_submitter`, and adaptor tests only with `hatch run integ:test_adaptor`.

The submitter tests work by running a script in Blender that generates a job bundle using the the Deadline Cloud addon. We then check the validity of the template and compare the bundle to what we expect.

The adaptor tests work by feeding params and a template to `openjd run` so that we don't have to take care of parsing and whatnot in the tests.

### What is the impact of this change?
More confidence in our changes.

### How was this change tested?
Ran the tests, I also made some changes to skip the save confirmation when creating a job bundle. I ensured this still showed up when using the UI. 

### Was this change documented?
Yep, added guidelines on running the tests to the `DEVELOPMENT.md`.

### Is this a breaking change?
Nope.

----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2025-01-03 20:51 UTC, miabatta requested changes
There are a few things I've asked about, but this is awesome! Super excited about the new tests 👯

2025-01-03 20:51 UTC, miabatta commented on test/integ/helpers/image_comparision.py
> +        # and put them in numpy arrays. Pillow doesn't have a good built-in way to do image comparision
spelling nit: comparision -> comparison (also will have to change the file name)

2025-01-03 20:51 UTC, miabatta commented on test/integ/test_blender.py
> +        "RenderEngine": "cycles",
Is there value in parameterizing the different render engines here? Or if not parameterizing, having different test cases for them? It comes to mind since the output can look quite different from engine to engine.

2025-01-03 20:51 UTC, miabatta commented on src/deadline/blender_submitter/addons/deadline_cloud_blender_submitter/open_deadline_cloud_dialog.py
> +    The internal variation exists so that the functionality can be accessed without a UI.
Great! I'd like to use this to improve the unit tests as well sometime soon.

2025-01-03 20:51 UTC, miabatta commented on test/integ/test_blender.py
> +def test_minimal_scene_submitter(
Forgive me if I'm rehashing old discussion here. But some of these tests seem like they could be added to the submitter unit tests. The `openjd check` makes sense in here IMO, but the template filling/parameter validation are covered in `test_submitter.py` (we'd have to add `asset_references` tests). Are there other advantages to having these as integ tests?

2025-01-03 21:05 UTC, edwards-aws commented on test/integ/helpers/image_comparision.py
> +        # and put them in numpy arrays. Pillow doesn't have a good built-in way to do image comparision
Oops, will fix.

2025-01-03 21:09 UTC, edwards-aws commented on test/integ/test_blender.py
> +        "RenderEngine": "cycles",
Not right now, as far as I know the only other engine we have to worry about here is Eevee, which is a GPU renderer as far as I know. We can't guarantee that everyone running these tests has a GPU on their machine. Being able to exclude certain tests based on the environment is something we will need to revisit in the future. For example if we want to test integrations with V-Ray, we won't be able to assume that everyone running that tests has the V-Ray plugin.

2025-01-03 21:13 UTC, edwards-aws commented on test/integ/test_blender.py
> +def test_minimal_scene_submitter(
The advantage of having these as integration tests is that we are testing how our submitters work with Blender.

Unit tests are great, you can write a lot of them and make them really specific to test our logic. However unit tests mock out the Blender API because the environment they run in doesn't have Blender available to it, or we're looking to test specific behaviour that's challenging to recreate in an integration test.

Another advantage to integration tests is that when Blender releases a new version, we can test that our assumptions are still true about the Blender API and nothing changed.

2025-01-03 21:26 UTC, miabatta commented on test/integ/test_blender.py
> +def test_minimal_scene_submitter(
Good point! Thanks for the clarification.

2025-01-03 21:43 UTC, miabatta commented on test/integ/test_blender.py
> +        "RenderEngine": "cycles",
I see what you mean! I did try submitting an EEVEE render to a CPU fleet and it rendered successfully (this was my hunch since I can render locally with it), so it is still an option if you think it's useful. (My assumption is that EEVEE/workbench automatically use GPUs whereas Cycles has to be explicitly set to)

2025-01-06 17:51 UTC, miabatta commented on test/integ/test_blender.py
> +        # We don't care what order the filenames list is in, so turn it into a set for easier comparision.
just the one! I don't mind approving though, we can go back and fix it later.

2025-01-06 17:51 UTC, miabatta approved these changes, later dismissed

2025-01-06 22:07 UTC, edwards-aws commented on test/integ/test_blender.py
> +        # We don't care what order the filenames list is in, so turn it into a set for easier comparision.
Oh wow I misspelled that again! I'll be back in this code again soon, so I'll make the fix there, or if another reviewer requests changes in this PR.

2025-01-07 21:30 UTC, lucaseck reviewed
Awesome to see @edwards-aws! I've left a couple of comments, but was also curious if you knew anything about https://github.com/aws-deadline/deadline-cloud-for-blender/blob/mainline/setup_integ_env.sh? Not sure if this was a previous attempt at integ tests and is now unused?

2025-01-07 21:30 UTC, lucaseck commented on test/integ/helpers/image_comparison.py
> +        assert np.allclose(actual, expected, atol=2)
Just curious, how did you come up with `atol=2` for the tolerance?

2025-01-07 21:30 UTC, lucaseck commented on test/integ/helpers/test_runners.py
> +    output = run_command(["openjd", "check", str(template_location), "--output", "json"])
Is openjd present in the hatch env or is this relying on it being somewhere on the system path?

2025-01-07 21:30 UTC, lucaseck commented on test/integ/test_scripts/minimal_test/_test_blend.py
> +def main(job_history_dir: str, output_dir: str):
nit: Can you include a description of what this test covers e.g. multiple layers, multiple cameras, just the basics etc?

2025-01-07 21:30 UTC, lucaseck commented on DEVELOPMENT.md
> +1. Set the environment variable `BLENDER_EXECUTABLE` to the location of the Blender application.
Can something be added to the PR template to ask if they've run the integ tests and point to the instructions here.

2025-01-07 21:33 UTC, lucaseck commented on test/integ/test_blender.py
> +    reason="There's a bug where multiple view layers are rendered when it should only be one.",
Is there a GitHub issue for this? I didn't see one at a quick glance.

2025-01-07 21:35 UTC, edwards-aws commented on test/integ/test_scripts/minimal_test/_test_blend.py
> +def main(job_history_dir: str, output_dir: str):
Can do

2025-01-07 21:35 UTC, edwards-aws commented on test/integ/test_blender.py
> +    reason="There's a bug where multiple view layers are rendered when it should only be one.",
I was gonna cut one after this is merged because this test is the repro case.

2025-01-07 21:36 UTC, edwards-aws commented on DEVELOPMENT.md
> +1. Set the environment variable `BLENDER_EXECUTABLE` to the location of the Blender application.
Sure, I was going to wait until we had more. But I guess there's no reason not to add it now.

2025-01-07 21:37 UTC, edwards-aws commented on test/integ/helpers/test_runners.py
> +    output = run_command(["openjd", "check", str(template_location), "--output", "json"])
Good catch! I meant to add this to the hatch env and it looks like I forgot.

2025-01-07 21:38 UTC, edwards-aws commented on test/integ/helpers/image_comparison.py
> +        assert np.allclose(actual, expected, atol=2)
Mostly a guess, it's low and seems to work. A more scientific way would be to run a couple renders from Blender and see how they usually differ.

2025-01-07 21:40 UTC, edwards-aws commented
> Awesome to see @edwards-aws! I've left a couple of comments, but was also curious if you knew anything about https://github.com/aws-deadline/deadline-cloud-for-blender/blob/mainline/setup_integ_env.sh? Not sure if this was a previous attempt at integ tests and is now unused?

I was unaware of this, I might remove it. It looks like it relies on a pretty specific setup with Blender in an S3 bucket.

2025-01-07 21:52 UTC, lucaseck commented on test/integ/helpers/image_comparison.py
> +        assert np.allclose(actual, expected, atol=2)
Figured as much, was just curious how much 2 actually translates to in terms of difference since in the numpy docs they're using very small values as the defaults.

2025-01-08 00:56 UTC, leongdl reviewed
Great job! 
Will have a second pass tomorrow ;)

2025-01-08 16:21 UTC, lucaseck approved these changes
🚢

2025-01-08 16:22 UTC, edwards-aws commented on test/integ/helpers/image_comparison.py
> +        assert np.allclose(actual, expected, atol=2)
I'll look at tightening this up when I add more tests.

2025-01-09 17:42 UTC, miabatta approved these changes
🚢

2025-01-09 17:45 UTC, leongdl approved these changes

2025-01-09 19:38 UTC, merged